require('options')
require('keymaps')
require('plugins')
require('configs.bufferline')
require('configs.treesitter')
require('configs.autopairs')
require('configs.nvimtree')
require('configs.lualine')
require('configs.indentline')
require('configs.telescope')
require('configs.lsp')
require('configs.cmp')

vim.cmd('colorscheme onedark')
vim.cmd('set background=dark')
