require("options")
require("keymaps")
require("plugins")
require("configs.autopairs")
require("configs.barbar")
require("configs.cmp")
require("configs.comment")
require("configs.gitblame")
require("configs.gitsigns")
require("configs.illuminate")
require("configs.indentline")
require("configs.jabs")
require("configs.legendary")
require("configs.lsp")
require("configs.lualine")
require("configs.neotest")
require("configs.nvimtree")
require("configs.telescope")
require("configs.test")
require("configs.toggleterm")
require("configs.treesitter")
require("configs.trouble")
require("configs.vsnip")
require("configs.whichkey")

-- require("configs.dap").setup()

vim.cmd([[ colorscheme gruvbox-material ]])
